### ISSUE TITLE
"did not reach completed state"

### ISSUE THREAD

**Issue by jamietsao** [remind101/stacker#400] opened 2017-06-13 23:33 UTC
I have a ECS cluster blueprint that creates the following resources:

- AWS::AutoScaling::LaunchConfiguration
- AWS::AutoScaling::ScalingPolicy (4 of these)
- AWS::CloudWatch::Alarm (4 of these)
- AWS::AutoScaling::AutoScalingGroup (2 of these)
- AWS::EC2::SecurityGroup
- AWS::AutoScaling::LaunchConfiguration
- AWS::IAM::InstanceProfile
- AWS::ECS::Cluster

After successfully building this stack, I tried updating 3 variables:
- different instance type & spot price for launch configuration 
- different min count for auto scaling group

When I tried re-running the `build` command, I got the following error:
```
[2017-06-13T16:26:36] DEBUG stacker.providers.aws.interactive:151(create_change_set): Attempting to create change set for stack: production-public-cluster.
[2017-06-13T16:26:36] DEBUG stacker.util:56(retry_with_backoff): Calling <bound method CloudFormation.create_change_set of <botocore.client.CloudFormation object at 0x10e59a410>>, attempt 1.
[2017-06-13T16:26:37] DEBUG stacker.util:56(retry_with_backoff): Calling <bound method CloudFormation.describe_change_set of <botocore.client.CloudFormation object at 0x10e59a410>>, attempt 1.
[2017-06-13T16:26:39] DEBUG stacker.util:56(retry_with_backoff): Calling <bound method CloudFormation.describe_change_set of <botocore.client.CloudFormation object at 0x10e59a410>>, attempt 1.
[2017-06-13T16:26:42] DEBUG stacker.util:56(retry_with_backoff): Calling <bound method CloudFormation.describe_change_set of <botocore.client.CloudFormation object at 0x10e59a410>>, attempt 1.
[2017-06-13T16:26:44] DEBUG stacker.util:56(retry_with_backoff): Calling <bound method CloudFormation.describe_change_set of <botocore.client.CloudFormation object at 0x10e59a410>>, attempt 1.
[2017-06-13T16:26:46] DEBUG stacker.util:56(retry_with_backoff): Calling <bound method CloudFormation.describe_change_set of <botocore.client.CloudFormation object at 0x10e59a410>>, attempt 1.
Traceback (most recent call last):
  File "/Users/jamie/.pyenv/versions/2.7.11/bin/stacker", line 9, in <module>
    args.run(args)
  File "/Users/jamie/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stacker/commands/stacker/build.py", line 52, in run
    dump=options.dump)
  File "/Users/jamie/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stacker/actions/base.py", line 124, in execute
    self.run(*args, **kwargs)
  File "/Users/jamie/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stacker/actions/build.py", line 283, in run
    plan.execute()
  File "/Users/jamie/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stacker/plan.py", line 267, in execute
    if not self._single_run():
  File "/Users/jamie/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stacker/plan.py", line 227, in _single_run
    status = step.run()
  File "/Users/jamie/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stacker/plan.py", line 74, in run
    return self._run_func(self.stack, status=self.status)
  File "/Users/jamie/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stacker/actions/build.py", line 228, in _launch_stack
    tags)
  File "/Users/jamie/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stacker/providers/aws/interactive.py", line 201, in update_stack
    tags, **kwargs)
  File "/Users/jamie/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stacker/providers/aws/interactive.py", line 165, in create_change_set
    cfn_client, change_set_id, sleep_time=2
  File "/Users/jamie/.pyenv/versions/2.7.11/lib/python2.7/site-packages/stacker/providers/aws/interactive.py", line 145, in wait_till_change_set_complete
    raise exceptions.ChangesetDidNotStabilize(change_set_id)
stacker.exceptions.ChangesetDidNotStabilize: Changeset 'arn:aws:cloudformation:us-west-1:728489771660:changeSet/change-set-1497396396/7b930b0f-0f90-4c84-897b-29443e228491' did not reach a completed state.
```

When I run the `diff` command, it says nothing has changed.

How do I debug this?

**Comment by jamietsao** [comment] 2017-06-15 00:14
Update: This only happens with the `-i` interactive flag.  That's kind of frustrating ...

**Comment by phobologic** [comment] 2017-06-19 15:42
Hey @jamietsao - sorry for the delay, been getting crushed by work.  There is a fix that has been merged, but we haven't released yet: https://github.com/remind101/stacker/pull/389

It's a strange edge case that we haven't been able to determine the cause of (it hits some people all the time, others - like Remind - almost never).  It doesn't seem to correlate with stack size, stack count, or anything.  Really strange.

Anyway, there's a "fix" (mostly it's just a lot more relaxed about the changeset taking a while) in place.  I'll try to get a release out early this week (possibly today).

**Comment by jamietsao** [comment] 2017-06-19 17:11
@phobologic - thanks for the update!  Looking forward to the release.

In general, what's the recommended way of asking questions related to stacker?  Just post an issue like this?

**Comment by phobologic** [comment] 2017-06-19 17:59
You can always ask here, no worries. There's also the slack team, which you can join at: https://empire-slack.herokuapp.com/  - there's a #stacker there, and plenty of folks who use/contribute to the tool who can answer your questions even if I'm swamped :)

I'm going to go ahead and close this, since I'm certain that PR will fix your issues.  Let me know if you want me to re-open it :)

**Closed by phobologic** 2017-06-19 17:59 UTC

**Comment by jamietsao** [comment] 2017-07-06 20:24
@phobologic - Any chance a release is coming out soon?

**Comment by phobologic** [comment] 2017-07-06 21:23
Sorry for the delay @jamietsao - https://github.com/remind101/stacker/releases/tag/1.0.3 is out now.  Please be sure to read the CHANGELOG entry (or the release itself) for some notes on some changed behavior.  For most people it's a no-op, but reading the docs will help with any confusion in case you're not one of those!

**Comment by jamietsao** [comment] 2017-07-06 21:57
@phobologic - Thank you!!!
